# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kmcapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kmcapp

  target 'kmcapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kmcappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'kmcapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kmcapp-tvOS

  # target 'kmcapp-tvOSTests' do
    # inherit! :search_paths
    # Pods for testing
  # end

end
